services:
  trackmycode.api:
    image: trackmycode.api
    build:
      context: .
      dockerfile: TrackMyCode.API/Dockerfile
    ports:
      - 5100:8080
      - 5001:8001
    environment:
      # Seq OpenTelemetry Exporter
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://trackmycode.seq:5341/ingest/otlp
#      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire OpenTelemetry Exporter
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://trackmycode.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc


  trackmycode.seq:
    image: datalust/seq:2024.3 # or latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - 8080:80
      - 5341:5341

  trackmycode.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888