name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Restore dependencies
      - name: Restore
        run: dotnet restore TrackMyCode.sln

      # Build the solution
      - name: Build
        run: dotnet build TrackMyCode.sln --configuration Release --no-restore

      # Run tests
      - name: Test
        run: dotnet test TrackMyCode.sln --configuration Release --no-restore --no-build
        # Solution/TrackMyCode.sln

      # Publish artifacts
      - name: Publish
        run: dotnet publish TrackMyCode.sln --configuration Release --no-restore --no-build