name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "9.x"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: TrackMyCode

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore TrackMyCode.sln

      - name: Build
        run: dotnet build TrackMyCode.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test TrackMyCode.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish TrackMyCode.sln --configuration Release --no-restore --no-build